server:
  port: 5050
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-master.yaml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO

# システム定数定義
system:
  constants:
    default:
      locale: ja
      date-format: uuuu-MM-dd
      time-format: hh:mm:ss
      date-time-format: uuuu-MM-ddThh:mm:ssSSS