server:
  port: 5050
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include: beans,health,metrics
mybatis:
  type-handlers-package: jp.co.molygray.**.typeHandler
  configuration:
    auto-mapping-behavior: FULL
    default-statement-timeout: 60
    map-underscore-to-camel-case: true
    log-prefix: mybatis-logger.

# システム定数定義
system:
  constants:
    default:
      locale: ja
      timezone: Asia/Tokyo
      date-format: uuuu-MM-dd
      time-format: hh:mm:ss
      date-time-format: uuuu-MM-ddThh:mm:ssSSS
